# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = HEXSPINBOX
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .

HEADERS = hexspinbox.h
SOURCES = hexspinbox.cpp \
		  main.cpp
QT +=gui
QT +=core
QT +=widgets
QT +=quick
QT +=core5compat
include(HEXSPINBOX.pri)
