# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = TestPlugs
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += $$PWD/lib/iconeditorplugin.lib
INCLUDERPATH += $$PWD/include
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
